DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "ADAM"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "KARL"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "BLUE"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "ADAM"

DEF RIVALNAME1 EQUS "RED"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "KARL"
ENDC
